env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb-base
  # - prettier
# parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  # - prettier
rules: 
  # prettier/prettier: error
  react/prop-types: 0
  import/extensions: 0
  no-console: 0

