steps:
  - name: Notify start deploy to Rollbar
    uses: rollbar/github-deploy-action@2.1.1
    id: rollbar_pre_deploy
    with:
      environment: 'production'
      version: ${{ github.sha }}
      status: 'started'
    env:
      ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
      ROLLBAR_USERNAME: ${{ github.actor }}

...

steps:
  - name: Notify finish deploy to Rollbar
    uses: rollbar/github-deploy-action@2.1.1
    id: rollbar_post_deploy
    with:
      environment: 'production'
      version: ${{ github.sha }}
      status: 'succeeded'
    env:
      ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
      ROLLBAR_USERNAME: ${{ github.actor }}
      DEPLOY_ID: ${{ steps.rollbar_pre_deploy.outputs.deploy_id }}
